/******************************************************************************
 * Module: ULTRASONIC SENSOR
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for ULTRASONIC SENSOR driver
 *
 * Author: Naiera Seifeldin
 *******************************************************************************/

/******************************** Includes ************************************/
#include "ultrasonic.h"
#include "gpio.h" // to set directions
#include "icu.h" // for ICU functions access
#include <util/delay.h>  // for delay

/***************************** Global variables *******************************/
static uint8 edgeCount = 0;
static uint16 timeHigh = 0; // we used uint16 as Timer1 is 16 bit

/*************************** Functions Definitions ****************************/
/* This function is used to initialize the ICU driver ,setup the ICU
 * call back function, initialize the Trigger pin direction as output pin */
void Ultrasonic_init(void)
{
	/* Configure ICU */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	/* Initialize ICU */
	Icu_init(&Icu_Config);
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Set Trigger pin as output */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,PIN_OUTPUT);

	/* Initialize Trigger pin by zero */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN ,LOGIC_LOW);
}

/* This function used to send trigger pulse to sensor */
void Ultrasonic_Trigger(void)
{
	/* Send the Trigger pulse ,, Triggering the sensor by setting this pin to HIGH for 10µs */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);
}

/* This function used to calculates distance measured by ultrasonic */
uint16 Ultrasonic_readDistance(void)
{
	Ultrasonic_Trigger(); /* send trigger pulse to Start measuring */

	/* We use polling to wait for ICU to measure 2 edges which are the first rising
	 * edge detected after triggering and the second edge which is falling one that
	 * detected when return back occurs */

	while(edgeCount != NUM_OF_EDGES);
	edgeCount=0;

	// Speed of sound = 346 m/s
    /* return of distance in Cm */
	return (timeHigh / 57.8);
}

/* This is the Call-Back Function called by ICU, called each edge, used to calculate
 * high time of the returned signal generated by ultrasonic pulse */
void Ultrasonic_edgeProcessing(void)
{
	 edgeCount++;
	if(edgeCount == 1) // if = 1 ,, signal of sensor has been sent
	{
		/* reset the timer value to start measuring from the
		 * first detected rising edge */
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING); /* make the ICU detect the falling edge */
	}
	else if(edgeCount == NUM_OF_EDGES) // if == 2 ,, signal returned then store T1
	{
		/* Store the High time value */
		timeHigh = Icu_getInputCaptureValue(); // T1
		/* making the ICU detect the rising edge for the next use of the sensor */
		Icu_setEdgeDetectionType(RISING);
	}
}

